name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps
        run: npm ci

      - name: Compile (Hardhat)
        run: npx hardhat compile

      - name: Run tests (Hardhat)
        run: npx hardhat test --network hardhat

      - name: Lint Solidity with solhint (optional)
        if: hashFiles('.solhint.json') != '' || hashFiles('.solhint.jsonc') != ''
        run: npx solhint 'contracts/**/*.sol'

  demo-build:
    name: Build demo (optional)
    runs-on: ubuntu-latest
    if: hashFiles('demo/package.json') != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache npm (demo)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-demo-${{ hashFiles('demo/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install demo deps
        working-directory: demo
        run: npm ci

      - name: Build demo
        working-directory: demo
        run: npm run build
